# Generated by Django 4.0.6 on 2022-07-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_brand_id_alter_category_id_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='city_name',
        ),
    ]
