# Generated by Django 4.0.6 on 2022-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Little Damaged', 'Little Damaged')], max_length=100),
        ),
    ]
